import { ArrowLeft, ArrowUpRight, CheckCircle2, Code2, ExternalLink, Image, Layers3, LockKeyhole, Search, Smartphone, Sparkles, Target, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SEO } from '@/components/layout/SEO';
import { Reveal, StaggerContainer, StaggerItem } from '@/components/ui/Reveal';
import { Button } from '@/components/ui/Button';
import { useRegion } from '@/hooks/useRegion';
import { toAbsoluteUrl } from '@/lib/env';

type ProjectDossier = {
  title: string;
  descriptor: string;
  industry: string;
  audience: string;
  status: string;
  url: string;
  image: string;
  overview: string;
  challenge: string[];
  objectives: string[];
  role: string[];
  features: Array<{ title: string; detail: string; benefit: string; seo: string }>;
  journey: Array<[string, string]>;
  mobile: string;
  seo: string[];
  technology: string;
  security: string;
  results: Array<[string, string, string]>;
  faq: Array<[string, string]>;
  links: Array<[string, string]>;
};

const dossier = (slug: string): ProjectDossier | null => {
  const common = {
    status: 'Public project available for review',
  };
  const projects: Record<string, ProjectDossier> = {
    'velora-estates': {
      ...common,
      title: 'Velora Estates', descriptor: 'Luxury real estate discovery and advisory experience', industry: 'Luxury real estate', audience: 'Property buyers, investors, and clients seeking private viewings', url: 'https://real-estate-jawrah-project.netlify.app/', image: '/assets/case-studies/velora/desktop.png',
      overview: 'Velora Estates presents exclusive homes, villas, penthouses, and investment-oriented residences through a cinematic property experience. The public site combines listing discovery, property detail routes, private viewing language, advisory guidance, location context, and a four-stage path from discovery to closing support.',
      challenge: ['Premium property decisions require more context than a generic listing grid.', 'High-value visitors need a clear route from visual interest to private consultation.', 'Property imagery, 3D presentation language, and service detail must work together without making the journey difficult to scan.'],
      objectives: ['Create a luxury real estate identity with a strong visual point of view.', 'Make featured properties and property detail routes easy to discover.', 'Explain advisory, viewing, negotiation, and closing support as a coherent journey.', 'Give high-intent visitors clear Explore Properties and Private Consultation actions.'],
      role: ['Strategy: mapped property discovery against advisory and private-viewing intent.', 'UX: structured featured estates, property detail routes, gallery, services, and contact actions.', 'UI: used cinematic imagery, depth, glass cards, animated counters, and restrained premium spacing.', 'Development: delivered the public responsive property experience and interactive presentation language.', 'SEO: created property-oriented headings, detail URLs, descriptive content, and internal paths for discovery.', 'Performance: treated image-heavy real estate media and motion as areas requiring responsive asset and loading review.'],
      features: [
        { title: 'Featured estates', detail: 'The homepage surfaces named listings such as Ocean Crown Villa, Skyline Penthouse, Emerald Residence, Palm Grove Mansion, Harbour Glass House, and Golden Ridge Villa with prices, bedrooms, baths, size or view context, private tour, 3D preview, and verified labels.', benefit: 'Visitors can compare a curated set of high-value options quickly.', seo: 'Named property content and individual detail URLs support property-specific search intent.' },
        { title: 'Property detail routes', detail: 'The public experience links each featured estate to its own property-detail route.', benefit: 'A visitor can move from a summary card into a focused property decision page.', seo: 'Unique detail URLs provide a place for property-specific title, description, imagery, and structured data.' },
        { title: 'Advisory process', detail: 'Discover, Curate, Negotiate, and Close explain the service path from lifestyle and investment requirements to handover and after-sales support.', benefit: 'The process makes a complex property service easier to understand.', seo: 'Process headings add useful context for luxury property advisory searches.' },
        { title: 'Private viewing CTA', detail: 'Private Viewings and Private Consultation are presented as primary high-intent actions.', benefit: 'The interface prioritizes qualified conversations rather than treating property browsing as the final step.', seo: 'Consultation language supports long-tail intent around luxury property viewings.' },
        { title: 'Interactive showcase', detail: 'The site presents smooth scroll, custom cursor, particle canvas, floating cards, animated counters, and responsive layouts as part of its public experience.', benefit: 'Motion reinforces the premium positioning and gives the property experience a distinct character.', seo: 'Motion is supportive rather than a substitute for crawlable property copy and links.' },
        { title: 'Location and trust context', detail: 'Property cards expose location or view cues, while the site frames the service around guidance, documentation, inspections, and closing support.', benefit: 'Visitors receive decision context beyond the image alone.', seo: 'Location and service terms help connect the brand to local and investment-related intent.' },
      ],
      journey: [['Discover', 'The visitor enters through a premium property proposition and curated visual storytelling.'], ['Explore', 'Featured estates and property routes provide a focused way to inspect available residences.'], ['Understand', 'Advisory, property context, gallery, and service content build confidence around the decision.'], ['View', 'Private tour and private consultation actions move qualified visitors toward direct contact.'], ['Proceed', 'The stated process continues through negotiation, documentation, inspections, closing, and after-sales support.']],
      mobile: 'The public design is described as responsive and uses card-led property discovery, short CTA labels, and a direct consultation route. A device-level tap-target, animation, and Core Web Vitals audit was not independently measured.',
      seo: ['Natural themes include luxury real estate, premium property, property listings, private property viewing, and real estate advisory.', 'Property detail routes should carry unique titles, H1s, image alt text, and Residence or RealEstateAgent schema only when entity details are accurate.', 'No rankings, traffic, enquiries, or conversion results are claimed.'],
      technology: 'The public preview confirms a responsive interactive frontend experience, but does not reliably verify its framework, database, hosting, 3D engine, or integrations.', security: 'No authentication, private storage, authorization, payment, or admin workflow was verifiable from the public preview.',
      results: [['Verified', 'Public preview live', 'The supplied Velora Estates URL is publicly accessible.'], ['Qualitative outcome', 'Curated property experience', 'The site visibly provides named properties, detail routes, advisory content, and viewing CTAs.'], ['Not measured', 'Business performance', 'No sales, leads, traffic, rankings, or conversion figures were supplied.']],
      faq: [['What makes this different from a generic real estate listing site?', 'It combines curated property presentation with cinematic visual direction, private viewing language, advisory stages, and closing-support context.'], ['Can visitors view individual properties?', 'Yes. The public homepage links featured estates to individual property-detail routes.'], ['Does the site include private viewing CTAs?', 'Yes. Private Tour, Private Viewings, and Private Consultation actions are visible in the public experience.'], ['Were 3D tours technically verified?', 'The preview labels listings with 3D preview language, but the underlying 3D implementation was not independently verified.'], ['What SEO should property pages use?', 'Each property should have unique metadata, descriptive headings, location context, image alt text, breadcrumbs, and accurate real-estate structured data.'], ['Were property sales or enquiry results measured?', 'No measurable commercial results were supplied or claimed.']],
      links: [['Web Development Sri Lanka', '/lk/web-development-sri-lanka'], ['UI/UX Design', '/ui-ux-design'], ['SEO Services Sri Lanka', '/lk/services/seo-services-sri-lanka']],
    },
    'jawrah-pixel': {
      ...common,
      title: 'Jawrah Pixel IT', descriptor: 'Premium agency website and digital systems showcase', industry: 'Digital agency and technology services', audience: 'Premium brands, retailers, service businesses, founders, and operators', url: 'https://jawrah-pixel-itpe.vercel.app/', image: '/assets/case-studies/jawrah-pixel/desktop.png',
      overview: 'Jawrah Pixel IT is the agency platform itself: a public technology and service experience that explains web design, ecommerce, jewellery and fashion websites, UI/UX, branding, SEO, dashboards, payment gateway integration, custom systems, maintenance, and the agency network.',
      challenge: ['A broad service offer needed a clear hierarchy instead of an undifferentiated list.', 'The platform needed to communicate both premium brand thinking and practical technical delivery.', 'Visitors needed paths for services, case studies, technology, plans, agents, login, and booking.'],
      objectives: ['Position Jawrah Pixel around strategy, design, engineering, and ongoing support.', 'Make service categories and starting price signals easy to compare.', 'Explain the discovery-to-launch process and connect it to booking.', 'Present digital products, dashboards, payment systems, and portals alongside marketing websites.'],
      role: ['Strategy: organized the public platform around buyer intent, service discovery, proof, process, and booking.', 'UX: created navigation to Services, Case Studies, Process, Agents, Dashboard, Tech, Plans, Book, Login, and Sign Up.', 'UI: established a premium black-and-gold agency direction with reusable service and case-study sections.', 'Development: delivered the public service platform, forms, routes, and responsive presentation visible at the supplied URL.', 'SEO: used service-specific headings, case-study links, technology content, FAQs, and booking paths.', 'Performance: structured a content-heavy agency site so users can enter through a service, project, technology, or consultation route.'],
      features: [
        { title: 'Service architecture', detail: 'The public site separates Web Design, Ecommerce Development, Jewellery Websites, Fashion Brand Websites, Furniture Showroom Websites, Restaurant Websites, UI/UX Design, Branding, SEO Optimization, Admin Dashboards, Payment Gateway Integration, Custom Systems, and Maintenance.', benefit: 'Visitors can identify the service closest to their business problem.', seo: 'Each service theme creates a natural internal-link and landing-page architecture.' },
        { title: 'Booking and inquiry form', detail: 'The public booking form asks for name, email, WhatsApp number, business name, project type, budget, preferred date, preferred time, and message.', benefit: 'The agency receives structured context before a consultation.', seo: 'Supporting copy around project types and services strengthens commercial service intent.' },
        { title: 'Technology directory', detail: 'The Tech section names React, Next.js, Supabase, Firebase, Node.js, PostgreSQL, Stripe, PayHere, OnePay, Netlify, Cloudflare, and SEO tools as agency capability content.', benefit: 'Prospects can understand the types of systems the agency discusses.', seo: 'Technology terms support developer and business-system discovery, but they are not proof of use on every project.' },
        { title: 'Process and care plans', detail: 'Discovery, Strategy & Planning, UI/UX Design, Development, Testing & Optimization, Launch, and Maintenance & Support are presented with Basic, Premium, and Enterprise care plans.', benefit: 'The platform explains what happens before launch and after it.', seo: 'Process and maintenance content supports service evaluation searches.' },
        { title: 'Agency proof surfaces', detail: 'The platform includes case studies, testimonials, FAQ, trust statements, service starting-price signals, and an agent network.', benefit: 'Different visitors can validate capability through proof, pricing orientation, or partnership routes.', seo: 'Structured proof content creates internal links and topical depth.' },
      ],
      journey: [['Discover', 'A visitor enters through a service, project, technology, or agency-positioning section.'], ['Evaluate', 'They compare service scope, price signals, technology capability, process, maintenance, and proof.'], ['Qualify', 'The booking form collects business and project context.'], ['Consult', 'The primary action directs the visitor toward a private consultation or business inquiry.'], ['Continue', 'Maintenance, agent, login, and dashboard routes support longer-term relationships.']],
      mobile: 'The public platform states a mobile-first priority and exposes compact service cards, booking CTAs, and responsive navigation. A full device-level audit was not independently measured.',
      seo: ['Natural themes include web design, ecommerce development, UI/UX design, SEO services, admin dashboards, payment integration, and custom digital systems.', 'Service pages, case studies, FAQ, technology pages, and process content form the strongest internal-link clusters.', 'Public testimonials and price signals are agency-site content, not verified project results for every portfolio item.'],
      technology: 'The supplied public site explicitly presents a technology capability directory, but the exact technology used to build this particular public preview was not independently verified.', security: 'The public platform describes secure payment and system capabilities as services; project-specific authentication, authorization, storage, and API controls were not verified here.',
      results: [['Verified', 'Public agency platform', 'The supplied Jawrah Pixel IT URL is publicly accessible.'], ['Qualitative outcome', 'Broad service architecture', 'The site visibly organizes premium websites, commerce, systems, SEO, dashboards, and support.'], ['Not measured', 'Agency performance', 'No independent traffic, sales, ranking, or conversion results are claimed.']],
      faq: [['What is Jawrah Pixel IT?', 'It is a public agency platform presenting Jawrah Pixel services, case studies, process, technology capability, booking, support, and agent-network routes.'], ['Can the site support ecommerce projects?', 'Ecommerce Development is presented as a service with catalog, checkout planning, order workflow, and analytics setup language.'], ['Does the site offer custom systems?', 'Yes. Custom Systems is presented with booking systems, internal portals, automation flows, and custom integrations as service themes.'], ['Are all listed technologies used on every project?', 'No. The public technology directory describes agency capability; project-specific stacks must be verified separately.'], ['How does a visitor begin a project?', 'The public booking flow collects business, project, budget, schedule, and message details.'], ['Are the agency metrics independently verified?', 'No. The public platform statements are not treated as independently measured case-study results.']],
      links: [['Web Design Sri Lanka', '/lk/services/web-design-sri-lanka'], ['Custom Software Development', '/int/custom-software-development'], ['Case Studies', '/case-studies']],
    },
    'shabnam-jewellers': {
      ...common,
      title: 'Shabnam Jewellers', descriptor: 'Luxury 22K gold, diamond, and bridal jewellery commerce experience', industry: 'Jewellery and luxury retail', audience: 'Jewellery customers, bridal buyers, collectors, and local showroom visitors in Akurana', url: 'https://shabnam-tau.vercel.app/', image: '/assets/case-studies/shabnam-jewellers/desktop.png',
      overview: 'Shabnam Jewellers is a Sri Lankan jewellery experience organized around 22K and 24K gold, silver, bridal sets, diamonds, custom orders, repairs, showroom pickup, WhatsApp consultation, and daily-rate context. The public site pairs product imagery with a showroom-led trust model rather than presenting jewellery as anonymous catalogue inventory.',
      challenge: ['Jewellery buyers need confidence in purity, weight, pricing, exchange conditions, and aftercare.', 'A broad collection needs clear categories for bridal, wedding, daily, men, women, diamond, and new-arrival intent.', 'High-value enquiries often need a conversation, product photos, reservation, or showroom visit rather than an anonymous checkout.'],
      objectives: ['Create a premium digital showroom for jewellery discovery.', 'Expose gold-rate context without presenting it as a final purchase quote.', 'Connect product discovery to WhatsApp price requests, custom orders, reservations, and showroom pickup.', 'Make local trust signals, repair support, exchange policy, and contact information easy to find.'],
      role: ['Strategy: connected collection discovery with rate context, showroom reassurance, and assisted purchase actions.', 'UX: structured products, try-on, appointment, wishlist, account, contact, and checkout routes exposed by the public site.', 'UI: used black velvet, gold reflections, model styling, macro imagery, and premium collection grids.', 'Development: delivered the visible responsive jewellery commerce and enquiry experience.', 'SEO: created category language around gold, bridal, diamonds, repairs, custom orders, and Akurana discovery.', 'Performance: the image-heavy presentation requires responsive sizing, compression, lazy loading, and measured mobile review.'],
      features: [
        { title: 'Daily gold rates', detail: 'The public homepage shows 22K GOLD, 24K GOLD, and SILVER rates with a note that rates are updated in-store before purchase and the final rate is confirmed at booking.', benefit: 'Customers receive useful price context without confusing an indicative rate with a final quote.', seo: 'Gold-rate and local jewellery terms support timely Sri Lankan search intent.' },
        { title: 'Collection architecture', detail: 'The public site links Bridal Royale, Heritage Necklaces, Diamond Rings, Earrings, Bangles & Bracelets, chains, men, women, diamond, and new-arrival categories.', benefit: 'Visitors can begin with an occasion, product family, or audience need.', seo: 'Category language supports product and local jewellery discovery.' },
        { title: 'Assisted purchase paths', detail: 'Ask Price, Custom Order, WhatsApp Reserve Now, showroom pickup, private viewing, and appointment actions are visible.', benefit: 'The journey respects the consultation-led nature of high-value jewellery buying.', seo: 'Commercial intent is supported by descriptive service and category content around each CTA.' },
        { title: 'Trust and aftercare', detail: 'Purity, weight, bill, hallmark or certificate details, eligible exchange, repair service, secure payment, deposit, and showroom pickup are described.', benefit: 'Trust is built through specific conditions rather than decorative claims alone.', seo: 'Policy and service pages add useful long-tail content and internal links.' },
        { title: 'Public account surfaces', detail: 'The footer exposes products, try-on, appointment, wishlist, account, story, and contact destinations.', benefit: 'The visible architecture supports discovery, consideration, and returning-customer paths.', seo: 'Unique, crawlable routes can support collection and service indexing when technically indexable.' },
        { title: 'Local proof', detail: 'The public site identifies 91E Matale Rd, Akurana, WhatsApp 077 088 9090, showroom hours, and Google review content.', benefit: 'Local customers can validate where and how to continue the conversation.', seo: 'Consistent NAP and local business markup are appropriate opportunities.' },
      ],
      journey: [['Discover', 'A visitor enters through gold, bridal, diamond, or collection imagery.'], ['Compare', 'They review categories, product photography, gold-rate context, purity, weight, and policy reassurance.'], ['Ask', 'Ask Price, WhatsApp, appointment, or custom-order routes support assisted decision-making.'], ['Reserve', 'The site presents showroom pickup, private viewing, and deposit-ready language.'], ['Care', 'Repair, exchange, and contact routes extend beyond the first purchase conversation.']],
      mobile: 'The public site emphasizes WhatsApp, reserve, appointment, and category actions suited to mobile-led jewellery discovery. A complete try-on, checkout, tap-target, and Core Web Vitals test was not independently performed.',
      seo: ['Natural themes include 22K gold jewellery, bridal jewellery Akurana, diamond rings, gold rates Sri Lanka, custom jewellery, jewellery repairs, and showroom pickup.', 'Product and category pages should use unique titles, descriptive H1s, image alt text, price/rate clarity, breadcrumbs, and Product schema only for genuine product entities.', 'Review and AggregateRating schema should only be used when the displayed review data is valid and eligible.'],
      technology: 'The public experience verifies rendered jewellery, collection, enquiry, and commerce surfaces but does not reliably verify the underlying framework, database, payment provider, or integrations.', security: 'The public site references secure payment and account surfaces; authentication, authorization, private storage, signed URLs, and payment controls were not independently verified.',
      results: [['Verified', 'Public jewellery experience', 'The supplied Shabnam URL is publicly accessible.'], ['Qualitative outcome', 'Trust-led luxury showroom', 'The site visibly combines rates, collections, policies, repairs, WhatsApp, and local showroom information.'], ['Not measured', 'Commercial performance', 'No sales, revenue, traffic, ranking, or conversion figures are claimed.']],
      faq: [['Does Shabnam show gold rates?', 'Yes. The public site shows indicative 22K, 24K, and silver rates and states that final rates are confirmed at booking.'], ['Can customers request custom jewellery?', 'Yes. Custom Order and private consultation language are visible.'], ['Is showroom pickup supported?', 'Yes. The site presents reserve-and-collect and showroom pickup information for Akurana.'], ['Does the site include repairs?', 'Yes. Repair and adjustment support is described in the public trust section and footer.'], ['Are account, wishlist, and try-on routes present?', 'Yes. Those destinations are exposed publicly, although every underlying interaction was not independently tested.'], ['What SEO matters most for a jewellery site?', 'Unique category and product content, purity and price clarity, local NAP, image alt text, policy links, and accurate Product or LocalBusiness schema.']],
      links: [['Ecommerce Development Sri Lanka', '/lk/ecommerce-development-sri-lanka'], ['Web Design Sri Lanka', '/lk/services/web-design-sri-lanka'], ['SEO Services Sri Lanka', '/lk/services/seo-services-sri-lanka']],
    },
    'aerovista-travels': {
      ...common,
      title: 'AeroVista Travels', descriptor: 'Premium travel, visa, Umrah, and concierge inquiry experience', industry: 'Luxury travel and tourism', audience: 'Pakistani travellers, families, corporate travellers, pilgrims, and high-touch concierge clients', url: 'https://aero-vista-jawrah-project.vercel.app/#home', image: '/assets/case-studies/aero-vista/desktop.png',
      overview: 'AeroVista Travels presents a Pakistan-focused premium travel concierge with bespoke tours, VIP Hajj and Umrah passages, visa assistance, luxury destinations, flight-class inquiry, private travel consultation, branch information, and WhatsApp contact.',
      challenge: ['Luxury travel customers need inspiration and practical next actions in the same experience.', 'Flight, destination, visa, Umrah, and concierge intent are different journeys that need separate entry points.', 'High-touch travel planning is better served by qualified enquiry than by claiming an unverified instant-booking flow.'],
      objectives: ['Position the service as a premium travel and concierge operation from Pakistan.', 'Give visitors destination, visa, Umrah, flight, and consultation routes.', 'Collect structured flight and bespoke-arrangement information for advisor follow-up.', 'Make branch, WhatsApp, and support access visible for Pakistani customers.'],
      role: ['Strategy: separated inspiration, flight enquiry, visa support, destination, and concierge journeys.', 'UX: designed form-led consultation routes and destination cards with clear next actions.', 'UI: used cinematic travel imagery, premium dark presentation, destination cards, and high-touch service language.', 'Development: delivered the public responsive travel experience and inquiry interface visible at the supplied URL.', 'SEO: organized destination, visa, Umrah, and Pakistani city language into crawlable sections.', 'Performance: image-heavy destination media and animation require responsive asset handling and measured network review.'],
      features: [
        { title: 'Flight class inquiry', detail: 'The public homepage exposes round trip, one way, and multi-city choices, departure and destination airports, dates, guests, cabin tier, preferred carrier, budget estimate, and bespoke arrangements.', benefit: 'A complex travel brief can begin with structured information.', seo: 'Flight and travel-intent labels create relevant semantic content around premium travel planning.' },
        { title: 'Destination discovery', detail: 'Popular destinations include the Maldives, Holy Makkah & Madinah, Dubai, and Turkey with package or visa context.', benefit: 'Visitors can enter through a destination before deciding how much concierge support they need.', seo: 'Destination-specific headings and image alt text support travel search themes.' },
        { title: 'Visa and Umrah routes', detail: 'The site presents UK, Schengen, UAE, Saudi, Hajj, and Umrah support language with direct WhatsApp concierge actions.', benefit: 'Users with urgent documentation or pilgrimage needs have a direct route to an advisor.', seo: 'Visa and pilgrimage terms create distinct high-intent content clusters.' },
        { title: 'Branches and contact', detail: 'Karachi, Lahore, and Islamabad branch details, phone numbers, WhatsApp, and global concierge language are visible.', benefit: 'Local users can choose a familiar contact context.', seo: 'Branch and city information supports local SEO when addresses and business details are accurate.' },
        { title: 'Client portal language', detail: 'The public page lists client portal categories including flight inquiry, elite holiday packages, sanctuary hotels, visa support, and Umrah comfort.', benefit: 'The information architecture signals different service workstreams.', seo: 'Portal labels add topical context, but a functioning authenticated portal was not verified.' },
      ],
      journey: [['Discover', 'A traveller enters through a destination, concierge, visa, Umrah, or flight proposition.'], ['Specify', 'They select travel type, route, dates, guests, cabin, carrier, budget, or arrangement needs.'], ['Enquire', 'The form clearly states that the inquiry tier does not execute payment operations.'], ['Consult', 'WhatsApp and branch routes connect the brief with a travel advisor.'], ['Coordinate', 'The site describes concierge, visa, booking, and transit support; actual fulfilment results are not claimed.']],
      mobile: 'The public experience exposes WhatsApp, destination cards, and inquiry controls suited to mobile travel research. Full mobile form testing, keyboard behavior, and performance measurement were not independently verified.',
      seo: ['Natural themes include luxury travel Pakistan, Pakistan travel concierge, Umrah packages, visa assistance, Maldives holidays, Dubai travel, and bespoke tours.', 'Destination, visa, and service pages should have unique metadata, geographic context, breadcrumbs, image alt text, and accurate Organization or TravelAgency schema where applicable.', 'No booking, traffic, or revenue results are claimed.'],
      technology: 'The public site confirms a responsive interactive travel frontend but does not reliably verify flight APIs, booking engines, databases, hosting, or integrations.', security: 'The form explicitly states that no payment operations execute at the inquiry tier. Authentication, payment security, and private client-portal controls were not verified.',
      results: [['Verified', 'Public travel concierge preview', 'The supplied AeroVista URL is publicly accessible.'], ['Qualitative outcome', 'Multi-intent travel architecture', 'The site visibly separates destinations, flight inquiry, visa, Umrah, branches, and concierge actions.'], ['Not measured', 'Travel performance', 'No bookings, revenue, traffic, rankings, or conversion data are claimed.']],
      faq: [['What travel services are presented?', 'The public site presents luxury travel, destinations, visa assistance, Hajj and Umrah passages, flight inquiry, and concierge support.'], ['Can visitors submit a flight inquiry?', 'Yes. The form exposes route, dates, guests, cabin, carrier, budget, and bespoke-arrangement fields.'], ['Does the inquiry form take payment?', 'The public form states that no payment operations are executed at the inquiry tier.'], ['Which Pakistani locations are shown?', 'Karachi, Lahore, and Islamabad branches are listed publicly.'], ['Is an authenticated client portal verified?', 'Client portal categories are mentioned, but a functioning authenticated portal was not independently verified.'], ['What SEO should a travel site prioritize?', 'Destination pages, visa and pilgrimage intent, city and branch information, descriptive imagery, internal links, and accurate travel-business schema.']],
      links: [['Custom Software Development', '/int/custom-software-development'], ['Web Development Agency', '/int/web-development-agency'], ['SEO Services Sri Lanka', '/lk/services/seo-services-sri-lanka']],
    },
    'the-famous': {
      ...common,
      title: 'The Famous', descriptor: 'Editorial global streetwear and archive commerce concept', industry: 'Premium streetwear and fashion', audience: 'Students, creators, entrepreneurs, athletes, and customers drawn to limited streetwear drops', url: 'https://the-famous-demo.netlify.app/', image: '/assets/case-studies/the famous/desktop.png',
      overview: 'The Famous is a Jawrah Pixel concept presentation for a premium streetwear label. It combines drop-led product discovery with campaign archives, material studies, silhouette comparisons, community content, Inner Circle membership language, and a clear notice that the preview may include placeholder or unfinished functionality.',
      challenge: ['A streetwear label needs a world and a product system, not only product cards.', 'Limited drops, archive storytelling, materials, community, and membership need distinct but connected paths.', 'Concept content must be clearly separated from verified production commerce functionality.'],
      objectives: ['Create a strong editorial identity around ambition, resilience, and modern streetwear.', 'Show how collections, products, material information, and campaign archives can work together.', 'Provide visible drop, membership, newsletter, and shop actions.', 'Make the concept status clear so presentation content is not mistaken for production results.'],
      role: ['Strategy: built the concept around drop scarcity, archive culture, product narrative, and community.', 'UX: structured collections, product cards, material modules, silhouette comparison, membership, social proof, and archive routes.', 'UI: used industrial editorial imagery, bold typography, campaign pacing, and a dark fashion-art-direction system.', 'Development: delivered the public concept presentation and its visible interactions; the preview itself states that some functionality may be unfinished.', 'SEO: created rich fashion, material, campaign, collection, and product language for future indexable routes.', 'Performance: the dense image and motion system should be measured and optimized before production launch.'],
      features: [
        { title: 'Drop-led commerce', detail: 'The preview exposes New Drops, products such as Grit Cargo Pant V1, Core Oversized Tee, Architect Heavy Tee, and Ambition Hoodie, prices, details, limited messaging, and an early-access action.', benefit: 'Visitors understand the release model and product context before deeper browsing.', seo: 'Product names, collection titles, and material terms support fashion product intent.' },
        { title: 'Material ecology', detail: 'The site explains 240 GSM cotton, 450 GSM French Terry, cotton-nylon tech, durability, construction, and fit protocols.', benefit: 'Material education helps shoppers evaluate why a garment is positioned as premium.', seo: 'Specific textile content supports long-tail searches beyond generic clothing terms.' },
        { title: 'Campaign and archive', detail: 'Featured collections, campaign archives, Origins, Discipline, Ambition, Community, Future, and the Studio create an editorial world around the garments.', benefit: 'Brand meaning and product discovery reinforce each other.', seo: 'Archive and campaign routes create non-transactional content depth and internal links.' },
        { title: 'Inner Circle', detail: 'The concept presents early access, private releases, archive access, member pricing, private showroom events, and a membership application.', benefit: 'The model gives the label a retention and community narrative.', seo: 'Membership and limited-drop language supports branded discovery but is not a verified production feature set.' },
        { title: 'Concept disclosure', detail: 'The public site explicitly says it is a concept demonstration and that content, performance, integrations, and UX will be completed during production development.', benefit: 'The audience can interpret the experience accurately.', seo: 'Transparent status prevents unsupported claims from becoming misleading case-study content.' },
      ],
      journey: [['Enter', 'Campaign and manifesto language establish the label before the shop action.'], ['Explore', 'Visitors move through collections, drops, archives, studio, materials, or silhouettes.'], ['Inspect', 'Product names, prices, fabric specifications, fit, and construction provide decision context.'], ['Join', 'Inner Circle and subscribe actions offer future access and release communications.'], ['Acquire', 'The concept presents acquisition actions, but production checkout and purchase completion are not verified.']],
      mobile: 'The preview is intended as a responsive concept with content-rich imagery, drop cards, and CTA routes. Mobile checkout, membership submission, tap targets, and performance were not independently tested.',
      seo: ['Natural themes include premium streetwear, global streetwear, heavyweight cotton clothing, limited drops, fashion archive, 450 GSM French Terry, and modern men\'s clothing.', 'Production SEO should use unique product and collection metadata, Product schema only for real purchasable products, descriptive alt text, and crawlable archive routes.', 'Concept claims such as satisfaction, membership counts, and durability metrics should not be treated as verified results.'],
      technology: 'The public preview does not reliably verify the framework, commerce engine, CMS, payment system, analytics, or integrations.', security: 'No production account, payment, membership, or private-data controls were verified; the concept disclosure explicitly limits claims about unfinished functionality.',
      results: [['Verified', 'Concept preview live', 'The supplied The Famous URL is publicly accessible and identifies itself as a concept presentation.'], ['Qualitative outcome', 'Editorial fashion system', 'The preview visibly combines products, drops, materials, archive, community, and membership concepts.'], ['Not measured', 'Commerce performance', 'No sales, revenue, customers, traffic, rankings, or conversion figures are claimed.']],
      faq: [['Is The Famous a production store?', 'The public site identifies itself as a concept demonstration and says some functionality may be unfinished.'], ['What product information is shown?', 'The preview shows product names, prices, collection context, material details, fit, and construction language.'], ['Does it include campaign archives?', 'Yes. Campaign archives and an editorial studio are significant parts of the experience.'], ['Is membership functionality verified?', 'Membership and Inner Circle flows are presented conceptually, but production behavior was not independently verified.'], ['Can Product schema be added?', 'Only for genuine indexable products with accurate price, availability, and product data in production.'], ['What is the main SEO opportunity?', 'Build unique product, collection, material, campaign, and archive pages without relying on duplicated campaign copy.']],
      links: [['Ecommerce Development Sri Lanka', '/lk/ecommerce-development-sri-lanka'], ['Branding', '/branding'], ['UI/UX Design', '/ui-ux-design']],
    },
    'amirah-jewellery': {
      ...common,
      title: 'Amirah', descriptor: 'Private luxury jewellery and bespoke atelier presentation', industry: 'Luxury jewellery and gemstones', audience: 'Luxury jewellery clients, bridal buyers, collectors, and bespoke consultation prospects', url: 'https://amira-preview-jawrah-pixel.netlify.app/', image: '/assets/case-studies/amirah jewellers/dektop.png',
      overview: 'Amirah is a private presentation concept for a luxury jewellery house. The public experience centers on featured collections, bespoke custom creation, bridal specialists, personal consultation, gemstone heritage, client stories, private showroom scheduling, and a clear disclosure that imagery, collections, and ecommerce functionality may be demonstration content.',
      challenge: ['Luxury jewellery requires an atmosphere of rarity while keeping consultation actions understandable.', 'Bespoke commissions need a narrative journey from idea to stone selection and viewing.', 'Concept content and verified production capability must remain clearly separated.'],
      objectives: ['Translate jewellery craftsmanship into a refined digital atelier.', 'Create clear collection, bespoke, bridal, gemstone, and consultation routes.', 'Use heritage and custody language to support trust without hiding the private-sales model.', 'Present the work as a concept preview rather than claiming production commerce results.'],
      role: ['Strategy: framed the experience around love, legacy, collection discovery, bespoke commission, and private viewing.', 'UX: organized collections, why-choose-us proof, custom journey, heritage, client stories, and consultation CTAs.', 'UI: used campaign imagery, atelier language, editorial pacing, and luxury presentation patterns.', 'Development: delivered the public concept presentation and its visible responsive interaction model.', 'SEO: created distinct themes around jewellery, diamonds, sapphires, bridal, bespoke commissions, and Sri Lankan heritage.', 'Performance: high-resolution campaign media should be optimized and measured before a production launch.'],
      features: [
        { title: 'Featured collections', detail: 'The public preview presents Diamond Collection, Ceylon Sapphire Collection, and Bespoke Custom Creations with exhibition actions.', benefit: 'Visitors can start from a category matching their buying or commissioning intent.', seo: 'Collection names and descriptive copy support luxury jewellery search themes.' },
        { title: 'Custom design journey', detail: 'Sketch & Graph and Select Sapphire describe an early bespoke process, with Begin Bespoke Journey as a CTA.', benefit: 'The commission path feels personal and staged rather than transactional.', seo: 'Bespoke jewellery and custom design language supports high-intent long-tail discovery.' },
        { title: 'Heritage and trust', detail: 'The preview discusses Sri Lankan gemstone heritage, natural and unheated language, inspection, certificates, sourcing, and private custody.', benefit: 'Specific trust themes provide context for a high-consideration purchase.', seo: 'Heritage, gemstone, certification, and origin terms create topical depth, but claims must be substantiated in production.' },
        { title: 'Private consultation', detail: 'Schedule Showroom View and WhatsApp Advisory actions are presented as the main conversion routes.', benefit: 'The site matches a bespoke luxury model where conversation precedes purchase.', seo: 'Consultation and private-viewing terms support commercial luxury intent.' },
        { title: 'Concept disclosure', detail: 'The public page says it is an exclusive concept presentation and that final content, customer experiences, ecommerce functionality, integrations, and requirements will be tailored during production.', benefit: 'Visitors can separate design direction from live operational functionality.', seo: 'Transparent disclosure protects content accuracy and trust.' },
      ],
      journey: [['Discover', 'Campaign and collection content introduce the house and its luxury proposition.'], ['Curate', 'Visitors explore diamonds, sapphires, bespoke creation, bridal, or gifting themes.'], ['Understand', 'Heritage, craftsmanship, sourcing, and client-story content builds context.'], ['Consult', 'Showroom and WhatsApp CTAs create a private advisory route.'], ['Commission', 'The concept presents a bespoke journey, but production order, payment, and fulfilment systems are not verified.']],
      mobile: 'The concept exposes short collection and WhatsApp actions suitable for mobile luxury discovery. Mobile gallery, form, booking, payment, and performance behavior were not independently audited.',
      seo: ['Natural themes include luxury jewellery, bespoke jewellery, bridal jewellery, Ceylon sapphires, diamond collection, private jewellery consultation, and Sri Lankan jewellery heritage.', 'Use Product, Organization, BreadcrumbList, and FAQ schema only where the underlying entities and content are genuine and indexable.', 'Do not use Review, AggregateRating, certification, or origin claims without valid supporting evidence.'],
      technology: 'The public concept does not reliably verify its framework, CMS, database, booking, ecommerce, or integration stack.', security: 'The public preview does not verify private viewing authentication, payment, private storage, or customer data protections.',
      results: [['Verified', 'Private presentation live', 'The supplied Amirah URL is publicly accessible and identifies itself as a concept presentation.'], ['Qualitative outcome', 'Atelier-led luxury direction', 'The experience visibly combines collections, bespoke journey, heritage, stories, and private consultation.'], ['Not measured', 'Commercial results', 'No sales, revenue, enquiries, traffic, rankings, or conversion figures are claimed.']],
      faq: [['What kind of experience is Amirah?', 'It is a private luxury jewellery and bespoke atelier presentation centered on collections, craftsmanship, heritage, and consultation.'], ['Does the site show collections?', 'Yes. Diamond, Ceylon Sapphire, and Bespoke Custom Creations are presented as featured collections.'], ['Is there a bespoke journey?', 'Yes. The preview presents a custom design journey beginning with sketching and stone selection.'], ['Is ecommerce functionality live?', 'The public disclosure says ecommerce functionality will be tailored during production, so live checkout is not claimed.'], ['Can private showroom consultations be requested?', 'Schedule Showroom View and WhatsApp Advisory actions are visible in the concept.'], ['Which schema is appropriate?', 'Use Organization, WebPage, BreadcrumbList, FAQPage, and Product only when accurate production entities exist.']],
      links: [['Branding', '/branding'], ['UI/UX Design', '/ui-ux-design'], ['Ecommerce Development Sri Lanka', '/lk/ecommerce-development-sri-lanka']],
    },
    'kamal-jewellers': {
      ...common,
      title: 'Kamal Jewellers', descriptor: 'Handcrafted 22K gold heritage and bridal showroom experience', industry: 'Jewellery, gold, and bridal retail', audience: 'Bridal buyers, families, jewellery customers, and showroom visitors in Akurana', url: 'https://kamal-jewelers.vercel.app/', image: '/assets/case-studies/kamal jewellers/desktop.png',
      overview: 'New Kamal Jewellers presents a family jewellery heritage rooted in Akurana and established in 1979. The public experience organizes bridal couture, handcrafted diamonds, gold filigree, rare gemstones, wedding bands, private bridal consultation, showroom details, WhatsApp advisory, and legacy storytelling.',
      challenge: ['A long-running family jewellery identity needs digital presentation that respects heritage without feeling dated.', 'Bridal and custom enquiries need more context than a simple product grid.', 'Showroom trust, location, hours, and private consultation must sit close to the visual collection experience.'],
      objectives: ['Preserve and express the 1979 family heritage in a premium digital format.', 'Create clear collection routes for bridal, diamonds, filigree, gemstones, and wedding bands.', 'Connect digital discovery to private viewing and bridal salon consultation.', 'Support local SEO through Akurana showroom information and consistent contact routes.'],
      role: ['Strategy: positioned heritage, collections, bridal service, showroom, and advisory as one journey.', 'UX: created collection indexes, private dialogue language, showroom CTA, and legacy proof sections.', 'UI: used editorial typography, gold imagery, spacious layouts, and a restrained heritage luxury system.', 'Development: delivered the public responsive showroom experience and visible enquiry routes.', 'SEO: structured local jewellery, 22K gold, bridal, Akurana, and collection language.', 'Performance: image-rich heritage storytelling requires responsive assets and mobile measurement before production claims.'],
      features: [
        { title: 'Collection index', detail: 'The public site presents Bridal Couture, Handcrafted Diamonds, Gold Filigree, Rare Gemstones, and Wedding Bands.', benefit: 'Visitors can enter through occasion, material, or product category.', seo: 'Distinct category language supports jewellery and bridal search intent.' },
        { title: 'Private bridal salon', detail: 'The site describes private dialogue, traditional Kandyan ensembles, modern bridal sets, custom fit, weight balancing, and Bridal Salon Entry.', benefit: 'High-consideration bridal customers receive a consultation-first path.', seo: 'Bridal salon, custom jewellery, and Akurana content support long-tail local discovery.' },
        { title: 'Showroom experience', detail: 'The public site lists 280/1 Matale Road, Akurana, Central Province, Monday-Saturday hours, and a Visit the Showroom action.', benefit: 'Customers know where and when physical evaluation can continue.', seo: 'Accurate NAP and LocalBusiness schema are appropriate local SEO opportunities.' },
        { title: 'Legacy proof', detail: 'Established 1979, family-owned trust, master goldsmith dialogue, and continuous devotion are presented as the brand proof layer.', benefit: 'The site explains why the business is more than a catalogue.', seo: 'Heritage content differentiates the brand for local and cultural jewellery searches.' },
        { title: 'Private advisory', detail: 'Schedule Private Visit and WhatsApp Advisory actions are visible for showroom and bespoke engagement.', benefit: 'The CTA hierarchy matches a physical, high-value buying model.', seo: 'Consultation and private-viewing language supports commercial intent.' },
      ],
      journey: [['Discover', 'Heritage and handcrafted jewellery positioning establishes the house.'], ['Explore', 'Visitors browse bridal, diamonds, filigree, gemstones, and wedding bands.'], ['Imagine', 'Private bridal and custom-fit content helps customers frame their requirements.'], ['Visit', 'Showroom and WhatsApp actions direct customers to physical or conversational support.'], ['Commission', 'The site describes a private custom dialogue; fulfilment and sales results are not claimed.']],
      mobile: 'The public experience uses collection cards, short private-viewing CTAs, WhatsApp advisory, and showroom details suited to mobile research. A full mobile interaction and performance audit was not independently measured.',
      seo: ['Natural themes include New Kamal Jewellers, 22K gold Akurana, bridal jewellery Sri Lanka, gold filigree, handcrafted diamonds, wedding bands, and private jewellery viewing.', 'LocalBusiness, Organization, BreadcrumbList, Product, and FAQ schema should be used only where factual entity data is available.', 'No local ranking, review, sales, or enquiry improvements are claimed.'],
      technology: 'The public site confirms a responsive heritage jewellery frontend but does not reliably verify framework, CMS, database, commerce, or integrations.', security: 'No authentication, payment, private storage, or protected customer workflow was verifiable from the public experience.',
      results: [['Verified', 'Public heritage showroom', 'The supplied Kamal Jewellers URL is publicly accessible.'], ['Qualitative outcome', 'Heritage-led discovery', 'The site visibly combines collections, bridal service, showroom, local context, and legacy storytelling.'], ['Not measured', 'Business performance', 'No sales, revenue, traffic, rankings, or conversion results are claimed.']],
      faq: [['What heritage does the site communicate?', 'It presents New Kamal Jewellers as established in 1979 with family-owned Akurana roots.'], ['Which jewellery categories are shown?', 'Bridal couture, handcrafted diamonds, gold filigree, rare gemstones, and wedding bands are presented.'], ['Is a showroom listed?', 'Yes. The public site lists 280/1 Matale Road, Akurana, with opening hours.'], ['Can visitors request bridal advice?', 'Yes. Private Bridal Salon Entry, Private Visit, and WhatsApp Advisory routes are visible.'], ['What local SEO matters here?', 'Accurate Akurana NAP, collection pages, bridal intent, showroom content, image alt text, and valid local schema.'], ['Were sales or customer results verified?', 'No measurable business results were supplied or claimed.']],
      links: [['Ecommerce Development Sri Lanka', '/lk/ecommerce-development-sri-lanka'], ['Web Design Sri Lanka', '/lk/services/web-design-sri-lanka'], ['SEO Services Sri Lanka', '/lk/services/seo-services-sri-lanka']],
    },
    'elite-elegant': {
      ...common,
      title: 'Elite Elegant', descriptor: 'Customized jewellery gifting and premium presentation experience', industry: 'Luxury gifting and jewellery presentation', audience: 'Gift buyers, couples, jewellery customers, and customers seeking personalized presentation in Sri Lanka', url: 'https://elite-elegent-jawrah-pixel.netlify.app/', image: '/assets/case-studies/elite elegant/desktop.png',
      overview: 'Elite Elegant presents customized jewellery gift boxes and premium gifting experiences. The public concept includes collections for rings, necklaces, bridal, gift sets, bracelets, and customized boxes, along with signature products, personalization steps, gallery content, bespoke order CTAs, concierge service, and a clear premium concept direction.',
      challenge: ['Gift shoppers need help choosing both the jewellery and the presentation around an occasion.', 'Customization options need to be understandable without overwhelming the emotional purchase journey.', 'A premium packaging brand must make the product, process, and consultation path feel connected.'],
      objectives: ['Position customized gift boxes as a premium gifting experience.', 'Create occasion and category-led discovery.', 'Explain personalization from jewellery selection to wrapping and delivery.', 'Give customers clear bespoke order and concierge actions.'],
      role: ['Strategy: organized gifting around collections, signature creations, personalization, gallery, and concierge.', 'UX: mapped the six-step process from choose jewellery to delivered with care.', 'UI: used product photography, category grids, soft luxury presentation, and editorial gallery pacing.', 'Development: delivered the public concept experience and visible category, product, CTA, and process sections.', 'SEO: created gifting, jewellery, customized box, proposal, anniversary, bridal, and Sri Lanka language.', 'Performance: image-heavy product and gallery content should be compressed and measured before production launch.'],
      features: [
        { title: 'Atelier collections', detail: 'The site presents Luxury Rings, Elegant Necklaces, Bridal Collection, Gift Sets, Bracelets, and Customized Boxes.', benefit: 'Customers can enter by product family or gifting need.', seo: 'Category names support gift and jewellery discovery searches.' },
        { title: 'Signature creations', detail: 'Visible products include Velvet Ring Box, Proposal Gift Set, Luxury Necklace Box, and Anniversary Gift Box with LKR prices and Request actions.', benefit: 'Concrete examples make the gifting proposition tangible.', seo: 'Product names, occasion language, price context, and descriptive copy support product intent.' },
        { title: 'Personalization process', detail: 'Choose Jewellery, Select Gift Box, Add Name, Personal Message, Luxury Wrapping, and Delivered with Care describe the customization path.', benefit: 'Customers understand what can be personalized before making an enquiry.', seo: 'Process copy supports custom gifting and occasion-related long-tail content.' },
        { title: 'Gallery and journal', detail: 'Shared Moments and Atelier Journal imagery extend the experience beyond a product list.', benefit: 'Visual proof helps visitors imagine the presentation and occasion.', seo: 'Descriptive gallery alt text and crawlable journal content can support image and editorial search.' },
        { title: 'Bespoke CTA', detail: 'Initiate Bespoke Order and Concierge Service are presented at the final conversion point.', benefit: 'The CTA respects cases where a fixed product is not enough.', seo: 'Bespoke gifting and concierge terms support high-intent discovery.' },
      ],
      journey: [['Occasion', 'The visitor enters through gifting, proposal, anniversary, bridal, or premium presentation.'], ['Browse', 'Collections and signature creations provide a focused starting point.'], ['Personalize', 'The six-step process explains jewellery, box, name, message, wrapping, and delivery choices.'], ['Request', 'Product Request, Bespoke Order, or Concierge Service actions start the conversation.'], ['Deliver', 'The concept describes delivery with care; fulfilment and ecommerce operations are not independently verified.']],
      mobile: 'The concept uses category cards, product request actions, and a staged personalization flow that can support mobile gifting research. Checkout, form, tap-target, and performance behavior were not independently audited.',
      seo: ['Natural themes include customized jewellery gift boxes, proposal gift sets Sri Lanka, anniversary gifts, bridal jewellery gifts, luxury packaging, and personalized jewellery gifting.', 'Use Product schema for genuine products with accurate offers; use FAQ and BreadcrumbList only when those page structures exist in production.', 'No gifting sales, order, ranking, or conversion results are claimed.'],
      technology: 'The public concept confirms a responsive visual gifting experience but does not reliably verify framework, ecommerce engine, payment, CMS, or integrations.', security: 'No account, payment, private customer data, or personalization storage controls were verifiable from the public concept.',
      results: [['Verified', 'Public gifting concept', 'The supplied Elite Elegant URL is publicly accessible.'], ['Qualitative outcome', 'Process-led gifting experience', 'The site visibly combines categories, products, personalization, gallery, and concierge actions.'], ['Not measured', 'Commerce performance', 'No sales, revenue, customer, traffic, ranking, or conversion data are claimed.']],
      faq: [['What does Elite Elegant sell?', 'The public experience presents customized jewellery gift boxes, rings, necklaces, bridal, gift sets, bracelets, and related premium presentation.'], ['Can gift boxes be personalized?', 'The concept presents name, message, texture, color, lining, wrapping, and wax-seal personalization steps.'], ['Are product prices visible?', 'Yes. The visible signature creations include LKR price signals and Request actions.'], ['Are online payments verified?', 'No. The public concept exposes request and concierge paths, but payment operations were not independently verified.'], ['Which SEO themes are relevant?', 'Customized gift boxes, proposal gifts, anniversary jewellery gifts, bridal gifts, and personalized luxury gifting.'], ['Are sales results available?', 'No measurable business results were supplied or claimed.']],
      links: [['Ecommerce Development Sri Lanka', '/lk/ecommerce-development-sri-lanka'], ['Branding', '/branding'], ['UI/UX Design', '/ui-ux-design']],
    },
    'jawrah-client-portal': {
      ...common,
      title: 'Jawrah Client Portal', descriptor: 'Authenticated project document access experience', industry: 'Client portal and business workspace', audience: 'Jawrah Pixel clients who have been issued portal credentials', url: 'https://www.jawrahpixel.online/', image: '/assets/case-studies/jawrah client portal/desktop.png',
      overview: 'Jawrah Client Portal is a focused access surface rather than a public marketing site. The supplied URL presents a Jawrah Pixel login screen asking users to enter a username and password provided by the agency to access project documents, with a remember-device option and an access portal action.',
      challenge: ['Project documents should not be exposed through a public marketing page.', 'Clients need a clear, low-friction entry point for private project materials.', 'The public surface must communicate the boundary between public agency content and credential-protected access.'],
      objectives: ['Create a recognizable client-specific access point.', 'Keep the public screen focused on authentication rather than unrelated content.', 'Set an expectation that project documents require issued credentials.', 'Provide a foundation that can be extended into a broader authenticated workspace if verified and required.'],
      role: ['Strategy: separated private project access from the public Jawrah Pixel website.', 'UX: reduced the entry flow to username, password, remember-device, and access actions.', 'UI: used a restrained portal presentation with Jawrah Pixel identity and explicit document-access language.', 'Development: delivered the public login surface visible at the supplied URL.', 'SEO: kept the portal purpose specific; private portal content should generally not be indexable.', 'Performance: the focused entry screen has a smaller public content surface than a marketing site.'],
      features: [
        { title: 'Credential gate', detail: 'The public screen asks for username and password provided by Jawrah Pixel before access to project documents.', benefit: 'Private materials are conceptually separated from public portfolio content.', seo: 'The login page should use noindex if it is not intended as a search landing page.', },
        { title: 'Remember device', detail: 'A Remember this device option is exposed on the login surface.', benefit: 'It can reduce repeated sign-in friction for returning clients, subject to secure implementation.', seo: 'This is an interaction feature, not an SEO surface; private account pages should not be indexed.' },
        { title: 'Focused portal identity', detail: 'The page uses Jawrah Pixel branding and a clear JAWRAH CLIENT PORTAL label.', benefit: 'Clients can distinguish the portal from unrelated login pages.', seo: 'A concise title and noindex policy are more appropriate than broad keyword targeting.' },
        { title: 'Document access promise', detail: 'The screen specifically says credentials provide access to project documents.', benefit: 'The purpose of the portal is clear before authentication.', seo: 'Public copy can explain the portal without exposing private project content.' },
      ],
      journey: [['Receive access', 'A client receives credentials from Jawrah Pixel.'], ['Open portal', 'They visit the dedicated portal URL.'], ['Authenticate', 'They enter username and password and may choose to remember the device.'], ['Access documents', 'The stated destination is project-document access after successful authentication.'], ['Continue privately', 'Any dashboard, storage, download, role, or audit behavior requires source or authenticated testing and is not claimed here.']],
      mobile: 'The public login surface is compact and should adapt well to smaller screens, but authenticated mobile behavior, keyboard handling, password recovery, and session persistence were not independently tested.',
      seo: ['The correct SEO posture is likely a focused title, clear brand purpose, canonical consistency, and noindex for private portal routes unless a public help page is intended.', 'Do not expose document titles, client names, private files, or dashboard content to crawlers.', 'Security and access claims require source review or authorized authenticated testing.'],
      technology: 'The public URL verifies a login interface only. It does not verify the framework, authentication provider, database, storage, session model, encryption, or deployment stack.', security: 'A username/password gate is visible. Authorization, hashing, MFA, sessions, protected storage, signed URLs, rate limiting, and audit logs were not verifiable from the public screen.',
      results: [['Verified', 'Public login surface', 'The supplied Jawrah Client Portal URL is publicly accessible and presents a credential form.'], ['Qualitative outcome', 'Private-access boundary', 'The portal clearly separates project-document access from public agency content.'], ['Not measured', 'Security and operations', 'No authenticated test, penetration review, storage audit, or usage metrics were supplied.']],
      faq: [['What is the Jawrah Client Portal?', 'It is a dedicated credential-entry surface for clients to access project documents issued by Jawrah Pixel.'], ['Is the portal publicly open?', 'The login surface is public, but it requires a username and password to proceed.'], ['Does the public screen prove secure storage?', 'No. Storage, authorization, session security, and document controls require source or authorized testing.'], ['Should the login page be indexed?', 'Usually no, unless there is a deliberate public portal-information page; private access screens should generally use noindex.'], ['Is a dashboard verified?', 'Only the login surface was verified from the supplied public URL. A post-login dashboard was not tested.'], ['Can this become a larger client workspace?', 'Yes as a product direction, but additional workspace features should be documented only after they are implemented and verified.']],
      links: [['Custom Software Development', '/int/custom-software-development'], ['Web Development Agency', '/int/web-development-agency'], ['Process', '/process']],
    },
    'miorah': {
      ...common,
      title: 'Miorah Gem & Jewellery', descriptor: 'Sri Lankan gemstone sourcing and private inquiry experience', industry: 'Gemstones and luxury jewellery', audience: 'Collectors, jewellers, investors, and international buyers seeking Sri Lankan gemstones', url: 'https://miorah-preview-jawrah-pixel.netlify.app/', image: '/assets/case-studies/miorah/dektop.png',
      overview: 'Miorah Gem & Jewellery is a concept preview focused on Sri Lankan gemstone heritage, natural and unheated stones, private sourcing, certification language, collection showcases, worldwide delivery, and a sourcing-desk inquiry flow for collectors and buyers worldwide.',
      challenge: ['Gemstone buyers require origin, treatment, laboratory, cut, clarity, and sourcing context.', 'Private sourcing is a consultation journey rather than a conventional retail checkout.', 'Rich gemstone imagery and technical terminology must remain understandable and trustworthy.'],
      objectives: ['Build a high-trust gemstone presentation around Sri Lankan heritage.', 'Create a vault-style discovery model for blue sapphire, Padparadscha, teal sapphire, spinel, and tourmaline.', 'Collect structured private sourcing inquiries including mineral class, carat, budget, and cut.', 'Make the concept status and evidence boundaries clear.'],
      role: ['Strategy: built a private exhibition and sourcing narrative rather than a mass retail catalogue.', 'UX: organized heritage, featured gemstones, sourcing pillars, showcase, contact, and inquiry desk routes.', 'UI: used vault, exhibition, inspection, and gemstone imagery language with a premium editorial rhythm.', 'Development: delivered the public concept presentation and inquiry surface visible at the supplied URL.', 'SEO: created gemstone, origin, treatment, certification, sourcing, and location-oriented content clusters.', 'Performance: detailed gemstone imagery needs responsive formats, dimensions, lazy loading, and measured performance review.'],
      features: [
        { title: 'Featured gemstone vault', detail: 'The public preview presents Royal Velvet Blue Sapphire, Oceanic Gradient Teal Sapphire, Golden Lotus Padparadscha Sapphire, and Empress Green Chrome Tourmaline with origin, treatment, cut, clarity, and inquiry actions.', benefit: 'Collectors receive structured context before contacting the sourcing desk.', seo: 'Specific gemstone names and attributes support high-intent product and research searches.' },
        { title: 'Sourcing pillars', detail: 'Sri Lankan gem heritage, natural gemstones, worldwide shipping, trusted international buyers, and ethical sourcing are presented as pillars.', benefit: 'The brand explains how it wants the sourcing relationship to be understood.', seo: 'Pillar content builds topical depth, but certification and ethical claims require real evidence.' },
        { title: 'Private inquiry', detail: 'The sourcing form asks for primary contact name, resident country, email, WhatsApp, target mineral class, and sourcing specifications such as carat, budget, and cut.', benefit: 'A specialist can receive a more useful brief than a generic contact message.', seo: 'Supporting copy creates semantic relevance around gemstone sourcing and collector intent.' },
        { title: 'Inspection and showcase', detail: 'Latest Gemstone Showcase content describes alluvial extraction, symmetrical calibration, collection audit, photomicrography, and certification.', benefit: 'Process content makes the product story more technical and credible.', seo: 'Educational process pages can support informational gemstone searches and internal linking.' },
        { title: 'Concept disclosure', detail: 'The preview states that it is a concept presentation by Jawrah Pixel and may include placeholder or unfinished content.', benefit: 'The audience can distinguish design direction from verified production operations.', seo: 'Transparent status prevents unsupported product and certification claims.' },
      ],
      journey: [['Discover', 'The visitor enters through Sri Lankan heritage and natural gemstone positioning.'], ['Examine', 'Vault cards expose origin, treatment, cut, clarity, and collection context.'], ['Validate', 'Sourcing, inspection, certification, and heritage content answer trust questions.'], ['Specify', 'The private inquiry form collects mineral, country, carat, budget, cut, and message details.'], ['Source', 'The stated next step is specialist follow-up; no purchase, delivery, or sourcing result is claimed.']],
      mobile: 'The concept uses short inquiry CTAs, gemstone cards, and WhatsApp support suitable for mobile collector research. Full mobile form, image, and performance testing was not independently performed.',
      seo: ['Natural themes include Sri Lankan gemstones, Ceylon sapphires, unheated gemstones, Padparadscha sapphire, private gemstone sourcing, gemstone certification, and Ratnapura or Elahera heritage.', 'Product and ImageObject schema should only describe genuine, indexable stones with accurate attributes; avoid fabricated ratings or certifications.', 'Worldwide shipping and ethical sourcing claims need evidence before being treated as verified SEO content.'],
      technology: 'The public concept verifies a rich responsive gemstone presentation but does not reliably verify its framework, CMS, database, inquiry backend, or integrations.', security: 'The public concept exposes an inquiry form and WhatsApp route; private sourcing data protection, authentication, storage, and secure document delivery were not verified.',
      results: [['Verified', 'Gemstone concept live', 'The supplied Miorah URL is publicly accessible and identifies itself as a concept preview.'], ['Qualitative outcome', 'Vault-led gemstone storytelling', 'The site visibly combines gemstone attributes, heritage, sourcing, inspection, and private inquiry.'], ['Not measured', 'Commercial or sourcing results', 'No sales, customers, sourcing volume, traffic, rankings, or conversion results are claimed.']],
      faq: [['What is Miorah?', 'Miorah is presented as a Sri Lankan gemstone and jewellery concept focused on private sourcing and collector inquiry.'], ['Which gemstones are shown?', 'The preview presents blue sapphire, Padparadscha sapphire, teal sapphire, spinel, and tourmaline themes.'], ['Can visitors submit sourcing specifications?', 'Yes. The inquiry surface asks for mineral class and specifications such as carat, budget, and cut.'], ['Is there a retail checkout?', 'The preview describes private inquiries and explicitly presents itself as a concept; retail checkout is not claimed.'], ['Can certification claims be used in SEO?', 'Only when the underlying certificates and claims are real, current, and available for the relevant stone.'], ['What is the strongest SEO opportunity?', 'Detailed, accurate gemstone pages combining origin, treatment, cut, clarity, imagery, sourcing context, and inquiry links.']],
      links: [['Branding', '/branding'], ['UI/UX Design', '/ui-ux-design'], ['Custom Software Development', '/int/custom-software-development']],
    },
    'zaza-clothing': {
      ...common,
      title: 'Zaza Clothing', descriptor: 'Premium streetwear collection and concierge commerce experience', industry: 'Fashion and clothing e-commerce', audience: 'Sri Lankan streetwear shoppers, creators, and customers seeking heavyweight everyday garments', url: 'https://zaza-clothing-jawrah-preview.netlify.app/', image: '/assets/case-studies/zaza clothing/desktop.png',
      overview: 'Zaza Clothing is a concept-led premium streetwear experience built around heavyweight fabrics, oversized cuts, slow drops, collections, product inspection, lookbook storytelling, WhatsApp sizing support, and a private-member narrative. The public preview also includes explicit concept-style claims and placeholder-style social and review content that should not be treated as independently verified results.',
      challenge: ['Streetwear customers need product detail, fit confidence, scarcity context, and visual identity in one journey.', 'Heavyweight garments require material and construction explanations beyond a product name.', 'Limited drops and concierge sizing need clear actions without making unverified scarcity or review claims.'],
      objectives: ['Create a premium fashion identity around comfort, simplicity, and urban grace.', 'Organize New Arrivals, Best Sellers, Trending Now, Hoodies, Tees, and Outerwear.', 'Make product imagery, sizing, stock language, lookbook content, and WhatsApp support easy to find.', 'Keep concept and placeholder content clearly distinguished from verified production outcomes.'],
      role: ['Strategy: connected collection browsing with material standards, lookbook, sizing concierge, community, and membership.', 'UX: designed product cards, quick inspection, filters, campaign frames, and direct WhatsApp actions.', 'UI: used editorial streetwear imagery, oversized typography, dense fabric language, and controlled scarcity cues.', 'Development: delivered the public concept storefront and visible collection, product, lookbook, and inquiry surfaces.', 'SEO: created fashion, streetwear, product, material, collection, and Sri Lankan search themes.', 'Performance: product galleries and campaign imagery require compression, responsive sizes, lazy loading, and measured mobile review.'],
      features: [
        { title: 'Featured collections', detail: 'New Arrivals, Best Sellers, and Trending Now provide collection-level entry points with Explore Items actions.', benefit: 'Visitors can browse by current interest rather than a single undifferentiated catalogue.', seo: 'Collection headings support fashion and product discovery intent.' },
        { title: 'Current drop products', detail: 'The public preview shows Zaza Essential Hoodie, Zaza Oversized Classic Tee, and Zaza Signature Varsity Jacket with prices, Select Size, quick inspect, limited-stock, and real-time stock language.', benefit: 'Customers receive product and fit context before starting a conversation.', seo: 'Descriptive product names, category, price, and stock content support product SEO when accurate.' },
        { title: 'Lookbook', detail: 'The Cold Drop, Colombo Sunsets, The Luxury Varsity, and Streetscape Retro create editorial frames around fabric, silhouette, and Sri Lankan seasonal context.', benefit: 'The lookbook helps customers imagine garments in use.', seo: 'Unique editorial copy and descriptive image alt text support non-transactional fashion search.' },
        { title: 'Sizing concierge', detail: 'The preview directs shoppers to WhatsApp for size consultations, custom color combinations, early access, and proportion checks.', benefit: 'Fit uncertainty can be handled through a direct human route.', seo: 'Sizing and fit guidance support long-tail fashion commerce content.' },
        { title: 'Community and membership', detail: 'Zaza Fits, creator styling, reviews, Inner Circle, early access, and limited-drop language are presented in the public preview.', benefit: 'The brand builds a community narrative around wearing and returning to the label.', seo: 'Community content can support branded discovery, but displayed review and member figures require verification.' },
      ],
      journey: [['Discover', 'The manifesto and collection language establish the streetwear identity.'], ['Browse', 'Visitors choose New Arrivals, Best Sellers, Trending Now, or product categories.'], ['Inspect', 'Product cards show imagery, price, size selection, and stock or quick-inspect cues.'], ['Consult', 'WhatsApp sizing and concierge routes reduce fit uncertainty.'], ['Acquire', 'The preview presents commerce actions, but completed checkout, sales, and purchase results are not independently verified.']],
      mobile: 'The visible architecture prioritizes product cards, Select Size actions, WhatsApp concierge, collection filters, and lookbook imagery for mobile shopping. A complete mobile checkout, touch, and performance audit was not independently measured.',
      seo: ['Natural themes include premium streetwear Sri Lanka, oversized clothing, heavyweight cotton, varsity jacket, oversized tee, hoodie, fashion collection, and sizing concierge.', 'Product schema requires genuine product data, accurate offers, availability, and stable product URLs; review schema requires legitimate review evidence.', 'Do not claim the displayed satisfaction, dispatch, scarcity, or sizing figures as verified business results.'],
      technology: 'The public preview verifies a responsive fashion frontend but does not reliably verify framework, ecommerce engine, inventory backend, payment, analytics, or integrations.', security: 'The public preview exposes WhatsApp, membership, and commerce language, but account, payment, stock synchronization, privacy, and customer-data controls were not verified.',
      results: [['Verified', 'Public fashion preview', 'The supplied Zaza Clothing URL is publicly accessible.'], ['Qualitative outcome', 'Collection and concierge system', 'The site visibly combines collections, products, lookbook, sizing support, community, and membership concepts.'], ['Not measured', 'Commerce performance', 'No sales, revenue, customers, traffic, rankings, or conversion results are claimed.']],
      faq: [['What does Zaza Clothing present?', 'It presents premium streetwear collections, heavyweight garments, lookbook content, sizing concierge, and community-led fashion discovery.'], ['Which products are visible?', 'The preview shows an Essential Hoodie, Oversized Classic Tee, and Signature Varsity Jacket with price and size-selection cues.'], ['Is WhatsApp sizing support available?', 'A WhatsApp concierge route is visibly presented for sizing and style consultation.'], ['Does the site show collections?', 'Yes. New Arrivals, Best Sellers, Trending Now, Hoodies, Tees, Outerwear, and lookbook themes are visible.'], ['Are stock and review numbers verified?', 'No. The preview displays such claims, but they are not treated as independently verified results.'], ['What SEO should a fashion site prioritize?', 'Unique product and collection pages, accurate Product schema, material and fit content, descriptive image alt text, and internal links.']],
      links: [['Ecommerce Development Sri Lanka', '/lk/ecommerce-development-sri-lanka'], ['Web Design Sri Lanka', '/lk/services/web-design-sri-lanka'], ['SEO Services Sri Lanka', '/lk/services/seo-services-sri-lanka']],
    },
  };
  return projects[slug] ?? null;
};

export function VerifiedPortfolioCaseStudy({ slug }: { slug: string }) {
  const project = dossier(slug);
  const { p } = useRegion();
  if (!project) return null;

  return (
    <main className="relative min-h-screen overflow-hidden theme-bg font-sans">
      <SEO title={`${project.title} Case Study | Jawrah Pixel`} description={`${project.descriptor}. Explore the verified Jawrah Pixel case study, UX approach, SEO structure, and project scope.`} canonicalUrl={toAbsoluteUrl(p(`/case-studies/${slug}`))} ogImage={project.image} keywords={[project.title, project.industry, `${project.industry} website`, 'Jawrah Pixel case study']} schemaData={{ '@type': 'CreativeWork', name: project.title, headline: project.title, description: project.overview, url: toAbsoluteUrl(p(`/case-studies/${slug}`)), image: toAbsoluteUrl(project.image), creator: { '@type': 'Organization', name: 'Jawrah Pixel' } }} />
      <div className="container relative z-10 mx-auto px-5 pb-24 pt-32 sm:px-6 lg:pt-44">
        <Link to={p('/case-studies')} className="group inline-flex items-center gap-3 text-[10px] font-mono font-bold uppercase tracking-[0.3em] theme-text-muted hover:text-brand-blue"><ArrowLeft size={14} className="transition-transform group-hover:-translate-x-1" /> Back to case studies</Link>
        <section className="mt-16 grid gap-12 border-b theme-border pb-20 lg:grid-cols-[1.2fr_0.8fr] lg:items-end lg:gap-20">
          <Reveal><span className="text-[10px] font-mono font-bold uppercase tracking-[0.4em] text-brand-blue">{project.industry}</span><h1 className="mt-6 max-w-5xl text-5xl font-display font-medium uppercase leading-[0.9] tracking-tight theme-text-primary sm:text-7xl lg:text-8xl">{project.title}</h1><p className="mt-8 max-w-3xl text-lg font-light leading-relaxed theme-text-muted">{project.descriptor}. {project.overview}</p><div className="mt-10 flex flex-wrap gap-4"><a href={project.url} target="_blank" rel="noreferrer"><Button size="lg">View live project <ArrowUpRight size={17} className="ml-2" /></Button></a><span className="inline-flex items-center border theme-border px-5 py-3 text-[10px] font-mono uppercase tracking-[0.2em] theme-text-caption">{project.status}</span></div></Reveal>
          <Reveal delay={0.1} className="border theme-border theme-card p-7 sm:p-9"><img src={project.image} alt={`${project.title} project preview`} className="aspect-[16/10] w-full object-cover" /><div className="mt-7 grid gap-5 text-[10px] font-mono uppercase tracking-[0.18em] theme-text-caption"><span><b className="mb-2 block text-brand-blue">Audience</b>{project.audience}</span><span><b className="mb-2 block text-brand-blue">Project type</b>{project.descriptor}</span></div></Reveal>
        </section>

        <section className="my-24 grid gap-14 border-b theme-border pb-24 lg:grid-cols-[0.7fr_1.3fr] lg:gap-24"><Reveal><span className="text-[10px] font-mono font-bold uppercase tracking-[0.4em] text-brand-blue">01 / Project overview</span><h2 className="mt-5 text-4xl font-display uppercase leading-none tracking-tight theme-text-primary sm:text-6xl">The work behind the experience.</h2></Reveal><div className="space-y-8"><p className="text-lg font-light leading-relaxed theme-text-secondary">{project.overview}</p><div className="grid gap-4 sm:grid-cols-2"><div className="border theme-border theme-bg-tertiary p-6"><Users className="mb-6 text-brand-blue" size={21} /><h3 className="font-display uppercase theme-text-primary">Target audience</h3><p className="mt-3 text-sm leading-relaxed theme-text-muted">{project.audience}</p></div><div className="border theme-border theme-bg-tertiary p-6"><Target className="mb-6 text-brand-blue" size={21} /><h3 className="font-display uppercase theme-text-primary">Project status</h3><p className="mt-3 text-sm leading-relaxed theme-text-muted">{project.status}. Year and delivery timeline were not publicly specified.</p></div></div></div></section>

        <section className="mb-24 grid gap-5 lg:grid-cols-3"><Reveal className="border theme-border theme-card p-8"><span className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-brand-blue">02 / Challenge</span><ul className="mt-7 space-y-4">{project.challenge.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed theme-text-muted"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-blue" />{item}</li>)}</ul></Reveal><Reveal className="border theme-border theme-card p-8"><span className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-brand-blue">03 / Objectives</span><ul className="mt-7 space-y-4">{project.objectives.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed theme-text-muted"><CheckCircle2 className="mt-0.5 shrink-0 text-brand-blue" size={16} />{item}</li>)}</ul></Reveal><Reveal className="border theme-border theme-card p-8"><span className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-brand-blue">04 / What Jawrah Pixel did</span><ul className="mt-7 space-y-4">{project.role.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed theme-text-muted"><Layers3 className="mt-0.5 shrink-0 text-brand-blue" size={16} />{item}</li>)}</ul></Reveal></section>

        <section className="mb-24"><Reveal className="mb-12 max-w-3xl"><span className="text-[10px] font-mono font-bold uppercase tracking-[0.4em] text-brand-blue">05 / Feature-by-feature analysis</span><h2 className="mt-5 text-4xl font-display uppercase leading-none tracking-tight theme-text-primary sm:text-6xl">The solution, explained in context.</h2></Reveal><div className="grid gap-5 lg:grid-cols-2">{project.features.map((feature, index) => <Reveal key={feature.title} delay={index * 0.03} className="border theme-border theme-card p-7 sm:p-9"><div className="flex gap-5"><span className="font-mono text-sm text-brand-blue">{String(index + 1).padStart(2, '0')}</span><div><h3 className="text-xl font-display uppercase theme-text-primary">{feature.title}</h3><p className="mt-5 text-sm leading-relaxed theme-text-secondary"><strong className="theme-text-primary">What it is:</strong> {feature.detail}</p><p className="mt-3 text-sm leading-relaxed theme-text-secondary"><strong className="theme-text-primary">User and business benefit:</strong> {feature.benefit}</p><p className="mt-3 text-sm leading-relaxed theme-text-secondary"><strong className="theme-text-primary">SEO role:</strong> {feature.seo}</p></div></div></Reveal>)}</div></section>

        <section className="mb-24 grid gap-14 border-y theme-border py-20 lg:grid-cols-[0.7fr_1.3fr] lg:gap-24"><Reveal><span className="text-[10px] font-mono font-bold uppercase tracking-[0.4em] text-brand-blue">06 / Conversion journey</span><h2 className="mt-5 text-4xl font-display uppercase leading-none tracking-tight theme-text-primary sm:text-6xl">From first impression to next action.</h2></Reveal><div className="space-y-5">{project.journey.map(([title, copy], index) => <Reveal key={title} delay={index * 0.04} className="flex gap-5 border-b theme-border pb-5"><span className="font-mono text-sm text-brand-blue">0{index + 1}</span><div><h3 className="font-display uppercase theme-text-primary">{title}</h3><p className="mt-2 text-sm leading-relaxed theme-text-muted">{copy}</p></div></Reveal>)}</div></section>

        <section className="mb-24 grid gap-5 md:grid-cols-2"><Reveal className="border theme-border theme-card p-8 sm:p-10"><Smartphone className="mb-7 text-brand-blue" size={23} /><span className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-brand-blue">07 / Responsive and mobile</span><h2 className="mt-5 text-3xl font-display uppercase theme-text-primary">Designed for the smaller screen, measured honestly.</h2><p className="mt-7 text-sm leading-relaxed theme-text-muted">{project.mobile}</p></Reveal><Reveal className="border theme-border theme-card p-8 sm:p-10"><Search className="mb-7 text-brand-blue" size={23} /><span className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-brand-blue">08 / SEO strategy</span><h2 className="mt-5 text-3xl font-display uppercase theme-text-primary">Search intent with evidence boundaries.</h2><ul className="mt-7 space-y-4">{project.seo.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed theme-text-muted"><CheckCircle2 className="mt-0.5 shrink-0 text-brand-blue" size={16} />{item}</li>)}</ul></Reveal></section>

        <section className="mb-24 grid gap-5 md:grid-cols-2"><Reveal className="border theme-border theme-card p-8 sm:p-10"><Code2 className="mb-7 text-brand-blue" size={23} /><span className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-brand-blue">09 / Technical implementation</span><h2 className="mt-5 text-3xl font-display uppercase theme-text-primary">What is technically verifiable.</h2><p className="mt-7 text-sm leading-relaxed theme-text-muted">{project.technology}</p></Reveal><Reveal className="border theme-border theme-card p-8 sm:p-10"><LockKeyhole className="mb-7 text-brand-blue" size={23} /><span className="text-[10px] font-mono font-bold uppercase tracking-[0.3em] text-brand-blue">10 / Security</span><h2 className="mt-5 text-3xl font-display uppercase theme-text-primary">Security claims stay scoped.</h2><p className="mt-7 text-sm leading-relaxed theme-text-muted">{project.security}</p></Reveal></section>

        <section className="mb-24"><Reveal className="mb-12 max-w-3xl"><span className="text-[10px] font-mono font-bold uppercase tracking-[0.4em] text-brand-blue">11 / Results and transformation</span><h2 className="mt-5 text-4xl font-display uppercase leading-none tracking-tight theme-text-primary sm:text-6xl">What the evidence supports.</h2></Reveal><div className="grid gap-px border theme-border md:grid-cols-3">{project.results.map(([label, value, copy]) => <StaggerContainer key={label}><StaggerItem className="theme-bg p-8"><span className="text-[10px] font-mono uppercase tracking-[0.3em] text-brand-blue">{label}</span><strong className="mt-5 block text-2xl font-display uppercase theme-text-primary">{value}</strong><p className="mt-4 text-sm leading-relaxed theme-text-muted">{copy}</p></StaggerItem></StaggerContainer>)}</div></section>

        <section className="mb-24"><Reveal className="mb-12 max-w-3xl"><span className="text-[10px] font-mono font-bold uppercase tracking-[0.4em] text-brand-blue">12 / Project FAQ</span><h2 className="mt-5 text-4xl font-display uppercase theme-text-primary sm:text-6xl">Questions worth answering.</h2></Reveal><div className="grid gap-4 md:grid-cols-2">{project.faq.map(([question, answer]) => <Reveal key={question} className="border theme-border theme-card p-7"><h3 className="flex gap-3 text-lg font-display uppercase theme-text-primary"><span className="text-brand-blue">+</span>{question}</h3><p className="mt-4 text-sm leading-relaxed theme-text-muted">{answer}</p></Reveal>)}</div></section>

        <section className="mb-24"><Reveal className="border theme-border theme-card p-8 sm:p-12"><span className="text-[10px] font-mono font-bold uppercase tracking-[0.35em] text-brand-blue">13 / Related capability</span><h2 className="mt-5 max-w-3xl text-4xl font-display uppercase theme-text-primary sm:text-6xl">The capability behind the project.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{project.links.map(([label, path]) => <Link key={path} to={p(path)} className="group border theme-border p-6 transition-colors hover:border-brand-blue"><span className="flex items-center justify-between gap-3 font-display uppercase theme-text-primary">{label}<ExternalLink size={15} className="text-brand-blue transition-transform group-hover:translate-x-1" /></span><span className="mt-5 block text-sm leading-relaxed theme-text-muted">Explore the Jawrah Pixel capability relevant to this project.</span></Link>)}</div></Reveal></section>

        <Reveal className="border-t theme-border pt-20 text-center"><Sparkles className="mx-auto mb-7 text-brand-blue" size={25} /><h2 className="text-4xl font-display uppercase theme-text-primary sm:text-6xl">Have a similar digital challenge?</h2><p className="mx-auto mt-6 max-w-2xl leading-relaxed theme-text-muted">Jawrah Pixel can help turn a complex brand, commerce, or business-system requirement into a clear digital experience with evidence-led strategy.</p><Link to={p('/contact')} className="mt-9 inline-block"><Button size="lg">Start a project <ArrowUpRight size={17} className="ml-2" /></Button></Link></Reveal>
      </div>
    </main>
  );
}
